### PR TITLE
Release

### PR DESCRIPTION
**Pull request by dpezto**

### CODE REVIEW

**Comment by clason** [comment]
You probably did not want to commit the `target` folder...

**Comment by clason** [comment]
Also, `tree-sitter generate` complains about
```
Warning: rule style is just a `seq` or `choice` rule with a single element. This is unnecessary.
Warning: rule number is just a `seq` or `choice` rule with a single element. This is unnecessary.
```
You probably want to fix that, since we had issues with the generated parser not behaving correctly in such cases. (It will also simplify the parser.)

**Comment by clason** [comment]
Also also, the generated parser has blown up from 12 Mbyte to 33 Mbyte with a LARGE_STATE_COUNT of over 14k (which handily beats the previous "winner" in nvim-treesitter, `systemverilog`); this is something you probably should address as well, since I predict people will start to complain (in nvim-treesitter...) about performance issues with the new version.

**Comment by dpezto** [comment]
Yeah, I pushed accidentally before fixing everything 🙃😅 it had been a while since I worked on this project and saw that `tree-sitter generate` created a lot of new files and I missed a few things in my `.gitignore`. Unfortunately I won’t have access to my computer until next week. As soon as I can I will revert back to before this push to at least make things work while I’m working on the parser.

**Comment by clason** [comment]
That's fine, then, if it's still WIP. I'll park the parser in nvim-treesitter then and prevent updates.

**Comment by clason** [comment]
@dpezto friendly ping :)

(Also, new tree-sitter 0.24.4 version out; you might want to regenerate the parser with that.)

**Comment by clason** [comment]
@dpezto are you still planning on reverting the changes to the `main` branch? If you are no longer working on this parser, this would be good to know so we can mark it as such at nvim-treesitter.

**Comment by dpezto** [comment]
Yes, sorry, life happened and got busy. I hope I'll get it done before the 22nd. 
Also I'm rewriting the grammar from the ground up. Hopefully it'll be ready before February

**Comment by dpezto** [comment]
Done. Now it should work as before. 😄

**Pull request merged**
